// <auto-generated />
using System;
using Budget.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Budget.Web.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260804081651_AddMerchantLogos")]
    partial class AddMerchantLogos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Budget.Web.Domain.Merchants.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_normalized");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_merchants");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_merchants_name_normalized");

                    b.ToTable("merchants", (string)null);
                });

            modelBuilder.Entity("Budget.Web.Domain.Merchants.MerchantAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MerchantId")
                        .HasColumnType("integer")
                        .HasColumnName("merchant_id");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_normalized");

                    b.HasKey("Id")
                        .HasName("pk_merchant_aliases");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_merchant_aliases_merchant_id");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_merchant_aliases_name_normalized");

                    b.ToTable("merchant_aliases", (string)null);
                });

            modelBuilder.Entity("Budget.Web.Domain.Transactions.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FollowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("follow_number");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<string>("IbanOtherParty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iban_other_party");

                    b.Property<bool>("IsNotFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_not_fixed");

                    b.Property<string>("NameOtherParty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_other_party");

                    b.Property<string>("NameOtherPartyNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_other_party_normalized");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("NameOtherPartyNormalized")
                        .HasDatabaseName("ix_transactions_name_other_party_normalized");

                    b.HasIndex("Iban", "FollowNumber", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_iban_follow_number_user_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Budget.Web.Domain.Merchants.MerchantAlias", b =>
                {
                    b.HasOne("Budget.Web.Domain.Merchants.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_aliases_merchants_merchant_id");

                    b.Navigation("Merchant");
                });
#pragma warning restore 612, 618
        }
    }
}
